apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kafka-producer
  labels:
    app: {{ .Release.Name }}-kafka-producer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kafka-producer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
