apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-akhq-config
data:
  application.yml: |
    akhq:
      connections:
        {{ .Values.kafka.clusterName }}:
          properties:
            bootstrap.servers: "{{ .Values.kafka.bootstrapServers }}"
