apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-akhq
  labels:
    app: {{ .Release.Name }}-akhq
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-akhq
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-akhq
    spec:
      containers:
        - name: akhq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: MICRONAUT_CONFIG_FILES
              value: "/app/application.yml"
          volumeMounts:
            - name: config
              mountPath: /app/application.yml
              subPath: application.yml
          ports:
            - name: http
              containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-akhq-config
